using Pkg; Pkg.add("JLD2")
using Pkg; Pkg.add("CSV")
Pkg.add("DataFrames")
Pkg.add("Plots")
Pkg.add("Missings")
Pkg.add("HypothesisTests")
Pkg.add("Distributions")
Pkg.add("Formatting")
Pkg.add("Logging")
